---
title: "CIS 600 Stock Clustering"
author: "Gafei Szeto, Greg Shin, Ashraf Elnashar"
date: "11/15/2019"
output: pdf_document
---

```{r}

```

library(pacman)


# load the data here

stockTradingData <- read.csv("")


## lets do an EDA
EDA should already be done here already


# Clean this up

## Show some pretty graphs about the initial/cleaned up data

Lets look to see wtf we have.

str(stockTradingData)

# Determine how this is clustered

# Determine what parameters this is getting clustered through

# Partitional Clustering?

# Hiearchical Clustering?

## K means Clustering? K is 4 here.

Play with your k value here to modify the clustering analysis.
This is our model for playing around with different type of data.

fit <- kmeans(stockTradingData, centers = 4, iter.max = 10000)

# Lets see what our output is

fit$centers
View(fit$centers)


# Divisive Clustering? 

# When do we tune?

# How do we measure "above average" perfomance? Percentage gain? 




Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
